name: Makefile CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Build the project
      run: make all

    - name: Test the project
      run: make all && chmod +x ./test/test.sh && ./test/test.sh | wc -l | grep 0